Fix nil access on client name
Some client windows like the toolbar (Form Controls) of Libre Office don't
have a name. The string concatenation with nil leads to an error and breaks
the whole menu.

    error: /home/joerg/.config/awesome/cheeky/util.lua:64: attempt to concatenate a nil value (field 'name')